version: '3'

services:
  zookeeper:
    image: zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - "2182:2182"
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181